accounts/urls.py
from django.urls import path

from .views import (
    LogInView, ResendActivationCodeView, RemindUsernameView, SignUpView, ActivateView, LogOutView,
    ChangeEmailView, ChangeEmailActivateView, ChangeProfileView, ChangePasswordView,
    RestorePasswordView, RestorePasswordDoneView, RestorePasswordConfirmView,
)

app_name = 'accounts'

urlpatterns = [
    path('log-in/', LogInView.as_view(), name='log_in'),
    path('log-out/', LogOutView.as_view(), name='log_out'),

    path('resend/activation-code/', ResendActivationCodeView.as_view(), name='resend_activation_code'),

    path('sign-up/', SignUpView.as_view(), name='sign_up'),
    path('activate/<code>/', ActivateView.as_view(), name='activate'),

    path('restore/password/', RestorePasswordView.as_view(), name='restore_password'),
    path('restore/password/done/', RestorePasswordDoneView.as_view(), name='restore_password_done'),
    path('restore/<uidb64>/<token>/', RestorePasswordConfirmView.as_view(), name='restore_password_confirm'),

    path('remind/username/', RemindUsernameView.as_view(), name='remind_username'),

    path('change/profile/', ChangeProfileView.as_view(), name='change_profile'),
    path('change/password/', ChangePasswordView.as_view(), name='change_password'),
    path('change/email/', ChangeEmailView.as_view(), name='change_email'),
    path('change/email/<code>/', ChangeEmailActivateView.as_view(), name='change_email_activation'),
]

app/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

from main.views import IndexPageView, ChangeLanguageView, post_image, profile_picture, post_interest, SearchPage, Liked, Follow, FriendList

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexPageView.as_view(), name='index'),
    path('post/', post_image, name='newpost'),
    path('liked/', Liked.as_view(), name='liked'),
    path('friends/', FriendList.as_view(), name='friends'),
    path('follow/<userid', Follow.as_view(), name='follow'),
    path('profilepicture/', profile_picture, name='profilepic'),
    path('interests/', post_interest, name='interests'),
    path('search/<s', SearchPage.as_view(), name='search'),
    path('i18n/', include('django.conf.urls.i18n')),
    path('language/', ChangeLanguageView.as_view(), name='change_language'),

    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.STATICFILES_URL, document_root=settings.STATICFILES_DIR)

main/models.py
from django.db import models
from django.contrib.auth.models import User


class UserInterests(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    interest = models.CharField(max_length=20)

class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.CharField(max_length=2000)
    img = models.ImageField(upload_to ='uploads/')
    time = models.DateTimeField()
    location = models.CharField(max_length=50)
    topic = models.CharField(max_length=20,blank=True)

class ProfilePic(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    img = models.ImageField(upload_to ='profilepics/')
    time = models.DateTimeField()

class Like(models.Model):
    post= models.ForeignKey(Post,on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE)

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.CharField(max_length=500)
    time = models.DateTimeField()

class Friend(models.Model):
    user1 = models.ForeignKey(User, on_delete=models.CASCADE,related_name='sender')
    user2 = models.IntegerField()
    accepted = models.BooleanField()
    time = models.DateTimeField()

main/views.py
from django.views.generic import TemplateView, DetailView, FormView, View, ListView
from django.contrib.auth.models import User
from .models import Post
from django.contrib import messages
from .models import Post, UserInterests, ProfilePic, Like, Comment, Friend
from .forms import PostForm, ProfilePictureForm, InterestForm, LikeSubmit, CommentSubmit
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import render, redirect
from .filtering import content_check
import datetime

class Liked(LoginRequiredMixin,TemplateView):
    model = Post
    template_name = 'main/liked.html'

    def get_context_data(self, **kwargs):
        context = {}
        context['object_list'] = Post.objects.all()
        context['liked_list'] = Like.objects.filter(user_id=self.request.user.id).order_by('-id')
        context['profilepics'] = ProfilePic.objects.all()
        context['comments_list'] = Comment.objects.all()
        context['users'] = User.objects.all()

        return context

class Follow(LoginRequiredMixin,TemplateView):
    template_name = 'main/follow.html'

    def get_context_data(self, **kwargs):
        query = self.request.GET.get('userid')
        model = Friend(user1=self.request.user,user2=query,accepted=1,time=datetime.datetime.now())
        if not Friend.objects.filter(user1=self.request.user,user2=query,accepted=1).count():
            model.save()
            messages.success(self.request,'User has been followed.')
            redirect('index')
        else:
            messages.warning(self.request,'User already followed')
            redirect('index')
        if self.request.method=='POST':
            redirect('index')

class FriendList(LoginRequiredMixin,TemplateView):
    model = Friend
    template_name = 'main/friends.html'

    def get_context_data(self, **kwargs):
        context = {}
        context['following_list'] = Friend.objects.filter(user1=self.request.user.id)
        context['follower_list'] = Friend.objects.filter(user2=self.request.user.id)
        context['users'] = User.objects.all()
        context['profilepics'] = ProfilePic.objects.all()
        return context


class SearchPage(TemplateView):
    model = Post
    template_name = 'main/search.html'

    def get_context_data(self, **kwargs):
        query = self.request.GET.get('search')
        context = {}
        context['all_posts'] = Post.objects.all().order_by('-id')
        context['object_list'] = Post.objects.filter(Q(text__icontains=query)).order_by('-id')
        context['location_list'] = Post.objects.filter(Q(location__icontains=query)).order_by('-id')
        context['profile_list'] = User.objects.filter(Q(first_name__icontains=query) or Q(last_name__icontains=query) or Q(username__icontains=query))
        context['profilepics'] = ProfilePic.objects.all()
        context['users'] = User.objects.all()
        context['comments_list'] = Comment.objects.all().order_by('-id')
        return context


class IndexPageView(View):
    template_name = 'main/index.html'
    form_class1 = LikeSubmit
    form_class2 = CommentSubmit

    def get(self, request):
        like_form = self.form_class1(None)
        comment_form = self.form_class2(None)
        context = {}
        context['user_count'] = User.objects.all().count()
        context['myinterests'] = UserInterests.objects.filter(user_id=self.request.user.id).values('interest')
        context['recommended'] = UserInterests.objects.filter(interest__in=context['myinterests']).filter(~Q(user_id=self.request.user.id)).values('user_id','interest')[:5]
        context['recommendedusers'] = User.objects.filter(id__in=context['recommended'].values('user_id')).order_by('?')
        context['post_count'] = Post.objects.all().count()
        context['comments'] = Comment.objects.all()
        context['connections'] = Friend.objects.all().count()
        context['users'] = User.objects.all()
        context['following'] = Friend.objects.filter(user1=self.request.user.id).values('user2')
        context['profilepics'] = ProfilePic.objects.all()
        context['myprofilepic'] = ProfilePic.objects.filter(user_id=self.request.user.id)
        context['userinterests'] = UserInterests.objects.all()
        context['posts'] = Post.objects.filter(Q(user_id__in=context['following']) | Q(user_id=self.request.user.id)).order_by('-time')[:30]
        return render(request, self.template_name, {'like_form': like_form, 'comment_form': comment_form,'context':context})


    def post(self, request):
        if self.request.method == 'POST':
            form1 = self.form_class1(request.POST)
            form2 = self.form_class2(request.POST)
            try:
                newform = form2.save(commit=False)
                check = content_check(newform.text)
                if not check:
                    newform.user_id = request.user.id
                    newform.time = datetime.datetime.now()
                    newform.save()
                else:
                    messages.warning(request,check)
                return redirect('index')
            except:
                newform = form1.save(commit=False)
                newform.user_id = request.user.id
                if not Like.objects.filter(user_id=request.user.id).filter(post_id=newform.post_id):
                    newform.save()
                return redirect('index')

def post_image(request):
    if request.method == 'GET':
        context = {}
        context['interests'] = UserInterests.objects.filter(user_id=request.user.id)
        context['profilepics'] = ProfilePic.objects.filter(user_id=request.user.id)

        return render(request, 'main/addPost.html', {'context': context})

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)


        if form.is_valid():
            newform = form.save(commit=False)
            newform.user_id = request.user.id
            newform.time = datetime.datetime.now()
            check = content_check(newform.text)
            if not check:
                newform.save()
                messages.success(request,'Your post has been uploaded successfully.')
            else:
                messages.warning(request,check)
            return redirect('index')
    else:
        form = PostForm()
    messages.warning(request,'Please Complete all fields')
    return render(request, 'main/addPost.html', {'form': form})

def post_interest(request):
    if request.method == 'GET':
        context = {}
        context['interests'] = UserInterests.objects.filter(user_id=request.user.id).order_by('interest')
        context['trending'] = UserInterests.objects.all().order_by('-id').values('interest').distinct()[:10]
        context['profilepics'] = ProfilePic.objects.filter(user_id=request.user.id)
        return render(request, 'main/addInterest.html', {'context': context})

    if request.method == 'POST':
        form = InterestForm(request.POST, request.FILES)

        if form.is_valid():
            newform = form.save(commit=False)
            newform.user_id = request.user.id
            newform.save()
            messages.success(request,'Interest Added')
            return redirect('interests')
        else:
            messages.warning(request,'Invalid Input')
            return redirect('interests')
    else:
        form = InterestForm()
    return render(request, 'main/addInterest.html', {'form': form})

def profile_picture(request):
    if request.method == 'GET':
        context2 = {}
        context2['existing'] = ProfilePic.objects.all()
        return render(request, 'main/profilepicture.html', {'context': context2})

    if request.method == 'POST':
        form = ProfilePictureForm(request.POST, request.FILES)
        if form.is_valid():
            newform = form.save(commit=False)
            newform.user_id = request.user.id
            newform.time = datetime.datetime.now()
            old = ProfilePic.objects.filter(user_id=request.user.id)
            old.delete()
            newform.save()
            return redirect('index')
    else:
        form = ProfilePictureForm()
    return render(request, 'main/profilepicture.html', {'form': form})

class ChangeLanguageView(TemplateView):
    template_name = 'main/change_language.html'

content/templates/main/addInterest.html
{% load static %}
{% load bootstrap4 %}

<html>
  <head>
    <title>SocioHub</title>
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <link rel="stylesheet" href="{% static 'feed.css' %}" />
    
    <script
      src="https://code.jquery.com/jquery-3.5.1.min.js"
      integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"
      integrity="sha384-LtrjvnR4Twt/qOuYxE721u19sVFLVSA4hf/rRt6PrZTmiPltdZcI7q7PXQBYTKyf"
      crossorigin="anonymous"
    ></script>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
      integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
      crossorigin="anonymous"
    />
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
      integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
      crossorigin="anonymous"
    ></script>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
      crossorigin="anonymous"
    />
    <style>
      /* Dropdown Button */
.dropbtn {
  background-color: #4caf50;
  color: white;
  padding: 16px;
  font-size: 16px;
  border: none;
  cursor: pointer;
}

/* Dropdown button on hover & focus */
.dropbtn:hover,
.dropbtn:focus {
  background-color: #3e8e41;
}

/* The search field */
#myInput {
  box-sizing: border-box;
  background-image: url("searchicon.png");
  background-position: 14px 12px;
  background-repeat: no-repeat;
  font-size: 16px;
  padding: 14px 20px 12px 45px;
  border: none;
  border-bottom: 1px solid #ddd;
}

/* The search field when it gets focus/clicked on */
#myInput:focus {
  outline: 3px solid #ddd;
}

/* The container <div> - needed to position the dropdown content */
.dropdown {
  position: relative;
  display: inline-block;
}

/* Dropdown Content (Hidden by Default) */
.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f6f6f6;
  min-width: 230px;
  border: 1px solid #ddd;
  z-index: 1;
}

/* Links inside the dropdown */
.dropdown-content a {
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
}

/* Change color of dropdown links on hover */
.dropdown-content a:hover {
  background-color: #f1f1f1;
}

/* Show the dropdown menu (use JS to add this class to the .dropdown-content container when the user clicks on the dropdown button) */
.show {
  display: block;
}

    </style>
    <script>
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#preview')
                    .attr('src', e.target.result)
                    .width(auto)
                    .height(auto);
            };

            reader.readAsDataURL(input.files[0]);
        }
    }
        let topics= [];
        //let imgSrc = "assets/images/clickhere.jpg";
        $( document ).ready(function() {
      
        //$("#profilePicture").attr("src", imgSrc);
          
        $(".form").change(function(){
          $("#submit").attr("disabled",false);
        });



        });

        function toggleInterest(value){
         
          if(topics.indexOf(value) ==-1 ){
            topics.push(value)
          }
          else{
            var index = topics.indexOf(value);
            if (index > -1) {
              topics.splice(index, 1);
               }
          }
          console.log(topics); 
          let stringI = "";
          topics.forEach(value =>{
              stringI= stringI + value;
              stringI+="<br/>";
          });
          document.getElementById("listInterest").innerHTML = stringI;
        }

        function myFunction() {
        
       document.getElementById("myDropdown").classList.toggle("show");
                              }

      function filterFunction() {
        console.log("function called");
        var input, filter, ul, li, a, i;
        input = document.getElementById("myInput");
        filter = input.value.toUpperCase();
        div = document.getElementById("myDropdown");
        a = div.getElementsByTagName("a");
        for (i = 0; i < a.length; i++) {
          txtValue = a[i].textContent || a[i].innerText;
          if (txtValue.toUpperCase().indexOf(filter) > -1) {
            a[i].style.display = "";
          } else {
            a[i].style.display = "none";
          }
        }
                                  }
    </script>
  </head>
  <body>
<nav class="navigation">
      <div class="navigation__column">
        <a href="{% url 'index' %}">
          <!-- Master branch comment -->
          <img src="{% static 'images/sociohublogo.png' %}" />
        </a>
      </div>
      <div class="navigation__column">
        <i class="fa fa-search"></i>
        <input type="text" placeholder="Search" />
      </div>
      <div class="navigation__column">
        <ul class="navigations__links" style="margin-bottom:auto;">
          <li class="navigation__list-item">
            <a href="explore.html" class="navigation__link">
              <i class="fa fa-chart-line"></i>
            </a>
          </li>
          <li class="navigation__list-item">
            <a href="addPost.html" class="navigation__link">
              <i class="fa fa-plus-square-o fa-lg" aria-hidden="true"></i>
            </a>
          </li>
          <li class="navigation__list-item">
            <a href="#" class="navigation__link">
              <i class="fa fa-heart-o fa-lg"></i>
            </a>
          </li>
          <li class="navigation__list-item">
            <a href="{% url 'accounts:change_profile' %}" class="navigation__link">
              <i class="fa fa-user-o fa-lg"></i>
            </a>
          </li>
          <li class="navigation__list-item">
            <a href="{% url 'accounts:change_profile' %}" class="navigation__link">
              {% for pic in context.profilepics %}
              {% if pic.user_id == request.user.id %}
              <img
                src="{{pic.img.url}}"
                style="float: right; width: 2.5rem; border-radius: 50%"
              />
              {% endif %}
              {% endfor %}
            </a>
          </li>
            <li class="navigation__list-item">
            <a href="{% url 'accounts:log_out' %}" class="navigation__link">
              Sign Out
            </a>
          </li>
        </ul>
      </div>
    </nav>
{% bootstrap_messages %}
    <div style="display: flex">

      <div id="feed" style="display: flex; width: 17%; margin-left: 3%">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
          <label for="id_interest">Add Interest</label>
          <input  name="interest" maxlength="200" class="form-control" placeholder="" title="" id="id_interest"></div>

        <button class="btn btn-info" type="submit">Update</button>
        <br>
        <hr>



    </form>
        </div>
      <div id="feed" style="display: flex; width: 17%; margin-left: 15%">
        <h3>My Added Interests:</h3>
          <ul>
          {% for interest in context.interests %}
              <h6><li>{{interest.interest}}</li></h6>
              {% endfor %}
          </ul>
      </div>

      <div id="feed" style="display: flex; width: 17%; margin-left: 15%">
        <h3>Recently Added Interests by Users:</h3>
          <ol>
          {% for trend in context.trending %}
              <h6><li>{{trend.interest}}</li></h6>
              {% endfor %}
          </ol>
      </div>

    </div>

  </body>
</html>

content/templates/main/addPost.html
{% load static %}
{% load bootstrap4 %}

<html>
  <head>
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <link rel="stylesheet" href="{% static 'feed.css' %}" />
    
    <script
      src="https://code.jquery.com/jquery-3.5.1.min.js"
      integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"
      integrity="sha384-LtrjvnR4Twt/qOuYxE721u19sVFLVSA4hf/rRt6PrZTmiPltdZcI7q7PXQBYTKyf"
      crossorigin="anonymous"
    ></script>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
      integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
      crossorigin="anonymous"
    />
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
      integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
      crossorigin="anonymous"
    ></script>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
      crossorigin="anonymous"
    />
    <style>
      /* Dropdown Button */
.dropbtn {
  background-color: #4caf50;
  color: white;
  padding: 16px;
  font-size: 16px;
  border: none;
  cursor: pointer;
}

/* Dropdown button on hover & focus */
.dropbtn:hover,
.dropbtn:focus {
  background-color: #3e8e41;
}

/* The search field */
#myInput {
  box-sizing: border-box;
  background-image: url("searchicon.png");
  background-position: 14px 12px;
  background-repeat: no-repeat;
  font-size: 16px;
  padding: 14px 20px 12px 45px;
  border: none;
  border-bottom: 1px solid #ddd;
}

/* The search field when it gets focus/clicked on */
#myInput:focus {
  outline: 3px solid #ddd;
}

/* The container <div> - needed to position the dropdown content */
.dropdown {
  position: relative;
  display: inline-block;
}

/* Dropdown Content (Hidden by Default) */
.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f6f6f6;
  min-width: 230px;
  border: 1px solid #ddd;
  z-index: 1;
}

/* Links inside the dropdown */
.dropdown-content a {
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
}

/* Change color of dropdown links on hover */
.dropdown-content a:hover {
  background-color: #f1f1f1;
}

/* Show the dropdown menu (use JS to add this class to the .dropdown-content container when the user clicks on the dropdown button) */
.show {
  display: block;
}

    </style>
    <script>
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#preview')
                    .attr('src', e.target.result)
                    .width(auto)
                    .height(auto);
            };

            reader.readAsDataURL(input.files[0]);
        }
    }
        let topics= [];
        //let imgSrc = "assets/images/clickhere.jpg";
        $( document ).ready(function() {
      
        //$("#profilePicture").attr("src", imgSrc);
          
        $(".form").change(function(){
          $("#submit").attr("disabled",false);
        });



        });

        function toggleInterest(value){
         
          if(topics.indexOf(value) ==-1 ){
            topics.push(value)
          }
          else{
            var index = topics.indexOf(value);
            if (index > -1) {
              topics.splice(index, 1);
               }
          }
          console.log(topics); 
          let stringI = "";
          topics.forEach(value =>{
              stringI= stringI + value;
              stringI+="<br/>";
          });
          document.getElementById("listInterest").innerHTML = stringI;
        }

        function myFunction() {
        
       document.getElementById("myDropdown").classList.toggle("show");
                              }

      function filterFunction() {
        console.log("function called");
        var input, filter, ul, li, a, i;
        input = document.getElementById("myInput");
        filter = input.value.toUpperCase();
        div = document.getElementById("myDropdown");
        a = div.getElementsByTagName("a");
        for (i = 0; i < a.length; i++) {
          txtValue = a[i].textContent || a[i].innerText;
          if (txtValue.toUpperCase().indexOf(filter) > -1) {
            a[i].style.display = "";
          } else {
            a[i].style.display = "none";
          }
        }
                                  }
    </script>
  </head>
  <body>
<nav class="navigation">
      <div class="navigation__column">
        <a href="{% url 'index' %}">
          <!-- Master branch comment -->
          <img src="{% static 'images/sociohublogo.png' %}" />
        </a>
      </div>
      <div class="navigation__column">
        <i class="fa fa-search"></i>
        <input type="text" placeholder="Search" />
      </div>
      <div class="navigation__column">
        <ul class="navigations__links" style="margin-bottom:auto;">
          <li class="navigation__list-item">
            <a href="explore.html" class="navigation__link">
              <i class="fa fa-chart-line"></i>
            </a>
          </li>
          <li class="navigation__list-item">
            <a href="" class="navigation__link">
              <i class="fa fa-plus-square-o fa-lg" aria-hidden="true"></i>
            </a>
          </li>
          <li class="navigation__list-item">
            <a href="" class="navigation__link">
              <i class="fa fa-heart-o fa-lg"></i>
            </a>
          </li>
          <li class="navigation__list-item">
            <a href="{% url 'accounts:change_profile' %}" class="navigation__link">
              <i class="fa fa-user-o fa-lg"></i>
            </a>
          </li>
          <li class="navigation__list-item">
            <a href="{% url 'accounts:change_profile' %}" class="navigation__link">
              {% for pic in context.profilepics %}
              {% if pic.user_id == request.user.id %}
              <img
                src="{{pic.img.url}}"
                style="float: right; width: 2.5rem; border-radius: 50%"
              />
              {% endif %}
              {% endfor %}
            </a>
          </li>
            <li class="navigation__list-item">
            <a href="{% url 'accounts:log_out' %}" class="navigation__link">
              Sign Out
            </a>
          </li>
        </ul>
      </div>
    </nav>
    <div style="display: flex">

      <div id="feed" style="display: flex; width: 17%; margin-left: 3%">
        {% bootstrap_messages %}
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
          <label for="id_text">Enter a caption</label>
          <textarea  name="text" maxlength="2000" class="form-control" placeholder="Caption in under 2000 characters..." title="" id="id_text"></textarea></div>
        <div class="form-group"><label for="id_img">Image</label>
          <input type="file" name="img" accept="image/*" onchange="readURL(this);" class="form-control-file" title="" required="" id="id_img">
        </div>

       <div class="form-row">
         <p>Choose an appropriate topic related to your post</p>
        <select class="form-control form-control-lg" name="topic" id="id_topic">
         {% for int in context.interests %}
         <option>{{int.interest}}</option>
         {% endfor %}
      </select>
       </div>
        <div class="form-group"><label for="id_location">Location</label>
          <input type="text" name="location" class="form-control"  id="id_location">
        </div>

        <button class="btn btn-primary" type="submit">Upload</button>

    </form>
        </div>
      <main id="feed" style="display: flex; padding: 0 0 0 10%">
        <h3>Preview</h3>
        <img id="preview" src="#" alt="Preview Unavailable" />
    </div>

  </body>
</html>

content/templates/main/change_language.html
{% extends 'layouts/default/page.html' %}

{% load i18n %}

{% block content %}

    {% get_current_language as language_code %}
    {% get_available_languages as languages %}

    <h4>{% trans 'Change language' %}</h4>

    <form action="{% url 'set_language' %}" method="post">

        {% csrf_token %}

        <input name="next" type="hidden" value="{{ redirect_to }}"/>

        <div class="form-group">
            <label class="form-control-label" for="language-field">{% trans 'Select the language' %}</label>
            <select name="language" class="form-control" id="language-field">
                {% for code, name in languages %}
                    <option value="{{ code }}" {% if code == language_code %} selected="selected"{% endif %}>
                        {{ name }} ({{ code }})
                    </option>
                {% endfor %}
            </select>
        </div>

        <button class="btn btn-success">{% trans 'Change' %}</button>

    </form>

{% endblock %}